### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by Alanin** [twonky4/ioBroker.spotify-premium#15]
https://github.com/twonky4/ioBroker.spotify-premium/blob/c18b70e3315c2dbb6a303df3f82b117668c6a8ff/main.js#L627

Seems that sometimes the function mentioned above is called with NULL instead of a STRING. this results in terminating the module.

Error Message from Log is attached

![screenshot 2018-05-08 05 41 35](https://user-images.githubusercontent.com/1335755/39736896-c08c1ca0-5282-11e8-8422-6448e3f569fe.png)

**Comment by Alanin** [comment]
Seems this error is raised when the playback is stopped and no title is playing so track_id can possibly  be 'null'

**Comment by twonky4** [comment]
But this shouldn't be the case. Do you now the playlist id and user id? So I can look in detail.

**Comment by Alanin** [comment]
I have made some Debug prints and have found the following...

This correspondents to PlaylistID, TrackName, TrackID

![screenshot 2018-05-08 08 53 05](https://user-images.githubusercontent.com/1335755/39742297-412d9824-529d-11e8-9a65-f4558c8eb0d5.png)

**Comment by Alanin** [comment]
Very interesting, that Track is not in the List when I check in Spotify...

![screenshot 2018-05-08 08 57 02](https://user-images.githubusercontent.com/1335755/39742463-d84c101e-529d-11e8-9fea-2be66311b531.png)

**Comment by xmace** [comment]
I have the same issue since the latest update of the spotify adapter. Always when i click "get user playlist" the spotify adapter crashes with the mentioned error message above.

**Comment by Alanin** [comment]
Thank you alot

**Comment by twonky4** [comment]
@xmace or @Alanin: Is the problem now fixed?

**Comment by Alanin** [comment]
@twonky4 Seems to be fixed. The error is no longer in the logs. Thank you a lot!
