### ISSUE TITLE
Playlist objects are not created

### ISSUE THREAD

**Issue by wendy2702** [twonky4/ioBroker.spotify-premium#2]
With Version 0.0.5 Playlists Objects are not created correct. Please see Picture at: [http://forum.iobroker.net/viewtopic.php?f=21&t=8173&p=125211#p125200](url)

This is how it should be:
[http://forum.iobroker.net/viewtopic.php?f=21&t=8173&p=125211#p125211](url)

**Comment by twonky4** [comment]
fixed with version 0.0.6
