### ISSUE TITLE
Do not generate objectds/tates with ",", "?", "[" and "]" in it!!

### ISSUE THREAD

**Issue by Apollon77** [twonky4/ioBroker.spotify-premium#23]
see https://github.com/ioBroker/ioBroker.js-controller/issues/198

According to observations in forum the adapter may create objects /state with unflitered names playlists and so nearly any character could be in there. this should be changed to a filtered list of characters (so maybe also not only remove the named above)

**Comment by twonky4** [comment]
also removed: "'*

**Comment by Apollon77** [comment]
thank you very much!!

**Comment by Apollon77** [comment]
Just after reading https://forum.iobroker.net/viewtopic.php?f=36&t=13700&p=145069#p150508 ... is replacing with same character really the best solution for harmony?  This user would have a lot of "duplicates" when you check his check script output
