### ISSUE TITLE
erron in request: 502

### ISSUE THREAD

**Issue by Mic-M** [twonky4/ioBroker.spotify-premium#29]
I have noticed this morning (was still on 0.2.4), that the error "erron in request: 502" appeared continuously in the ioBroker log for every 5 seconds. So I updated to 0.3.0, but it is still there.
Looks like Spotify changed "something". Unfortunately I do not have time to look into this any further at this time as I am out of town and will be back in a week.
However wanted to make sure this issue is being reported.
Thanks.

**Comment by twonky4** [comment]
@Mic-M: Any new infos here?

**Comment by Mic-M** [comment]
I could resolve the issue by deleting all Alexa devices and playlists and update these accordingly.
