### ISSUE TITLE
State "spotify-premium.0.player.playlist.trackNo" starts with 0 and not with 1

### ISSUE THREAD

**Issue by Mic-M** [twonky4/ioBroker.spotify-premium#36]
Hi,
I use adapter version 0.3.1 and the state "spotify-premium.0.player.playlist.trackNo" starts with 0 and not with 1 for showing the current playlist number: So if you select track #1 of the playlist, the state shows #0. Looks like the array value of the playlist is set into the state without incrementing by +1. 
Thanks.

Workaround for HTML in vis:
{v:spotify-premium.0.playbackInfo.playlist.trackNo; Number(v)+1}

**Comment by twonky4** [comment]
It's not a bug. The `spotify-premium.0.playbackInfo.playlist.trackNo` should show 0 for the first track. Also if you want to start playing the first track you have to put 0.

I will change the description of the state to descripe that it's 0-based and starts with 0.
