### ISSUE TITLE
play any track/album/playlist with spotify URI

### ISSUE THREAD

**Issue by bullrandle** [twonky4/ioBroker.spotify-premium#50]
In combination with [maddox/magic-cards](https://github.com/maddox/magic-cards/tree/master/docs) this would enable an easy way of automatic playlist handling. 
One then just needs a raspberry with an RFID reader which after reading an NFC Tag, sends the URI via MQTT to iobroker and iobroker then starts the track/album/playlist. 

I will try to add this myself, but since I'm really new to github, iobroker and java etc. this will take me a while.

BR
Christian

**Comment by twonky4** [comment]
Great Idea! I think the implementation should be easy. If you want to implement it, keep going. Otherwise I can add the support in half an hour.

**Comment by bullrandle** [comment]
Please do it, as I said, I'm just diving into iobroker etc.

**Comment by twonky4** [comment]
Will be a part of version 1.1.0

**Comment by bullrandle** [comment]
I'm trying to get this working but when I enter e.g.: {"context_uri":"spotify:artist:6e9wIFWhBPHLE9bXK8gtBI"} 
I get  "error in request: 400" in the iobroker log.
Am I missing something?

**Comment by bullrandle** [comment]
sendRequest('/v1/me/player/play?' + querystring.stringify(query), 'PUT', **send**).catch(function(err) {
instead of 
JSON.stringify(send) 
did the trick, now it works.

**Comment by maddingamer** [comment]
> sendRequest('/v1/me/player/play?' + querystring.stringify(query), 'PUT', **send**).catch(function(err) {
> instead of
> JSON.stringify(send)
> did the trick, now it works.

Could you explain that a little more please? I'm having same issuies with error 400...

**Comment by maddingamer** [comment]
> sendRequest('/v1/me/player/play?' + querystring.stringify(query), 'PUT', **send**).catch(function(err) {
> instead of
> JSON.stringify(send)
> did the trick, now it works.

I can confirm this. Line 1777 has to change as bullrandle said. Then using playURI works :)
